### ISSUE TITLE
SRAM_SIZE_MAX in stm32c011xx.h is wrong

### ISSUE THREAD

**Issue by pieterconradie** [STMicroelectronics/STM32CubeC0#1]
Hi there!

See:
https://github.com/STMicroelectronics/STM32CubeC0/blob/main/Drivers/CMSIS/Device/ST/STM32C0xx/Include/stm32c011xx.h#L501C1-L501C89

`#define SRAM_SIZE_MAX         (0x00001500UL)  /*!< maximum SRAM size (up to 6 KBytes) */`

Please correct me if I'm wrong :) The comment is correct. The SRAM size is 6k but the HEX value is wrong. It must be 0x00001800UL

Regards,
Pieter
https://piconomix.com

**Comment by TOUNSTM** [comment]
ST Internal Reference: 158657

**Comment by TOUNSTM** [comment]
Fixed in 1ffd3ef670a60938d0c8eaeb253fb94993bf4eed
