### ISSUE TITLE
ST Link driver installation issue

### ISSUE THREAD

**Issue by ghost** [STMicroelectronics/STM32CubeC0#2]
**Caution**
The Issues are strictly limited for the reporting of problem encountered with the software provided in this project.
For any other problem related to the STM32 product, the performance, the hardware characteristics and boards, the tools the environment in general, please post a topic in the [ST Community/STM32 MCUs forum](https://community.st.com/s/group/0F90X000000AXsASAW/stm32-mcus) 

**Describe the set-up**
 * The board (STM32 - NUCLEOC031C6)
 * IDE - keiluvision Version - 5
 
**Describe the bug**
Unable to install the ST link driver 

**Screenshots**
![image](https://github.com/STMicroelectronics/STM32CubeC0/assets/161560053/f7a71f03-93e6-4fba-9d54-af91a9dea40b)

**Comment by ghost** [comment]
Procedure:
   In device manager >other devices>ST-Link Debug>Update drive

![image](https://github.com/STMicroelectronics/STM32CubeC0/assets/161560053/157761c0-148f-452e-ad1b-d29b38480820)
![image](https://github.com/STMicroelectronics/STM32CubeC0/assets/161560053/d8fdebc8-e78f-4a4c-9b60-e3a75d22cf9a)

**Comment by ghost** [comment]
![image](https://github.com/STMicroelectronics/STM32CubeC0/assets/161560053/c15abdd6-7078-439a-a4dd-60d4219dea9a)


kindly check

**Comment by ALABSTM** [comment]
Hi @A23Velvizhi,

As mentioned in the **CONTRIBUTING.md** guide, this support channel is exclusively dedicated to issues related to the software published within this repository.

https://github.com/STMicroelectronics/STM32CubeC0/blob/e23a3ad670a74f2b6f9257801e84262046909071/CONTRIBUTING.md?plain=1#L38-L40

I suggest to submit your question to the [ST Community](https://community.st.com/s/topiccatalog). There, you will surely find the help you need to overcome your problem.

Please allow me to close this thread. Thank you for your comprehension and good luck.

With regards,
